### ISSUE TITLE
Get rid of Message Dialog from Youtube?

### ISSUE THREAD

**Issue by dun198** [Capevace/BetterPiP#1]
The app seems to work for me after I've got some problems at first.
Not sure if enabling the picture-in-picture chrom flag was the solution, but somehow it works now.
So thank you for your great work on this one. Was looking for something like this on chrome for quite some time. 

The only thing that's still bugging me a little bit is, when I click the chrome extension on Youtube a message dialog pops up with a long URL (shortened it):
```
betterpip://open?url=https%3A%2F%2Fr2---sn-4g5e6nls.googlevideo.com%2Fvideoplayb
ack%3Fmt%3D1522330741%26ratebypass%3Dyes%[...]
```

After clicking "OK" it opens the PiP view where I can watch the Video.

So, is it possible to somehow get rid of that first message so it directly opens the PiP video?

**Comment by Capevace** [comment]
Hi,

Sorry, but I‘m not actively maintaining this project anymore. My guess is that the message appears due to some new chrome policies...

Feel free to fork the project and try to fix it yourself!

**Comment by dun198** [comment]
Thanks for your response. I'll make sure to have a look at the code and see what I can do :)

**Comment by dun198** [comment]
Fixed it.

**Comment by Capevace** [comment]
Hey,

mind sharing what you changed? Im interested in what the fix was 😊
I could merge a PR if you’d like ✌🏻

**Comment by dun198** [comment]
Just commented out ``alert(a.href)`` in utils.js (line 32), so it's a pretty simple fix.
Maybe I will send some PR in the future since I'm currently playing around with the code a bit.

Stuff I did / want to do (only if I can do it without spending too much time):
- removed some unneccessary code
- application now quits when the PiP-Player is closed
- hope I can make the PiP-Player open automatically when the app launches from the browser extension
    - at the moment you have to click to open the app and click again to open the player
- fix PiP-Player not starting automatically
    - when the PiP-Player opens, it is in "playing" state, but the video won't start playing unless I click pause and play again (maybe a new version of the Pip.framework will fix this)
    - for now I changed it to open the player in paused state so I can press play when the video appears
- when closing the PiP-Player change the web pages video position to the current seek position

**Comment by dun198** [comment]
Ok now I successfully achieved the following behavior:

- single click on the chrome extension launches the app, opens the PiP-Video and starts playing automatically
- pressing "x" also terminates the app
- pressing "return to non-PiP" just closes the video window and keeps the app running
- opening the app without the chrome button isn't possible, so the app only starts when a valid url is found on applicationDidLaunch()

The only problem remaining is sometimes when you close the player and reopen it, the app will not launch until you press any control on the youtube player and retry.

**Comment by Capevace** [comment]
Awesome stuff!

**Comment by dun198** [comment]
fixed Notification not popping up when no video is found.
I'll probably upload a fork soon.

New ToDo:
- add Share extension, so BetterPiP will work with any app that can share URLs for example Safari or DeskApp
     - since BetterPiP works differently than Safari it can still play the Video while the tab or the browser is closed, so it could make sense to use BetterPiP in Safari as well, instead of the built in solution
    - also BetterPiP works with two-finger-swipe to seek, which also does not work in Safari's own PiP-mode
- (maybe) make it possible to open "locked" Youtube Videos / live streams, since some Videos won't open at the moment
- (maybe) expand support for more sites

**Comment by Capevace** [comment]
Great!

If you want, I could also just add you as a collaborator on Github.

**Comment by dun198** [comment]
Thank you for the offer. Not sure about that, since I'm not really experienced with Github.
I'm not a developer and also quite the beginner when it comes to programming.

**Comment by Capevace** [comment]
It just means you'd be able to push your changes to this repo without needing to send a pull request. :)

**Comment by dun198** [comment]
Well you could do that, but not sure if the push will be successful, since I also made some changes to the structure.

For now I made a fork where I pushed my changes here:
https://github.com/Dunkeeel/BetterPiP

If you want you can have a look at it and tell me if something is wrong with it.
Plus I also updated it to Swift 4 and I don't know if you would like that or not.
