### ISSUE TITLE
Is it possible to get some instructions on how to build this?

### ISSUE THREAD

**Issue by BrianGilbert** [Capevace/BetterPiP#3]

**Comment by Capevace** [comment]
Hey sorry for the late reply. Im not actively maintaining this atm, but if you wanna build it just open the xcode project and you _should_ (i hope :)) be able to just press run. For the chrome/firefox extension, youll need to enable development mode and point the browser to the extension folder path so itll get loaded. Should work smoothly from there.

I might make a proper build at some point but im not too sure.

Feel free to create PRs though if you want to add something to the project :)
